### ISSUE TITLE
Please help / how to use it

### ISSUE THREAD

**Issue by ricubuntu** [bigbluebutton/bbb-events#10]
Dear Fred,
I need to extract simple data about my meetings (attendee name, joining day/time, leaving day/time).
I understood that I have to use bbb-events ruby gem that has in it all the info I need.
But I'm not an expert with ruby and gems so I'm here to ask you if there is a guide on how to use it step by step to install it and to extract the data I need from events.xml file of my meeting.
I want to study and learn so I hope you can give me some advice to get through this.  
Thank you very much for everything.
Riccardo

**Comment by alexanderjackson** [comment]
It did not work on Ubuntu 16.04 and 20.04 for me. However, I got it working with the following steps in Ubuntu 18.04:

1. Install ruby, bundler and git:

```bash
apt update
apt install ruby ruby-bundler git -y
```
2. Clone the repo
```bash
cd /usr/src/
git clone https://github.com/bigbluebutton/bbb-events.git
cd bbb-events/
```

3. Install the dependencies
```bash
bundle install --path vendor/bundle
```

4. Now save your events file to `./events.xml`

5. Then extract the data from `./events.xml` like this:
```bash
bundle exec ./example.rb ./events.xml
```
6. The extraction should have created these two files:

```bash
root@bbb-events:/usr/src/bbb-events# ls -ahl data.*
-rw-r--r-- 1 root root 171 Jun  9 21:37 data.csv
-rw-r--r-- 1 root root 735 Jun  9 21:37 data.json
```

Hope this helps getting started..

**Comment by jstiger2469** [comment]
@alexanderjackson bundle exec ./example.rb ./events.xml how could i do this in a ruby script

Thanks

**Comment by alexanderjackson** [comment]
> @alexanderjackson bundle exec ./example.rb ./events.xml how could i do this in a ruby script
> 
> Thanks

Not sure what you mean. ` ./example.rb` is already a ruby script which is executed with bundler.
