### ISSUE TITLE
problem with install....

### ISSUE THREAD

**Issue by yannvautrin** [bigbluebutton/bbb-events#11]
Trying to install bbb-event following the instructions, here is what I get:

bundle install --path vendor/bundle
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: con                                               stant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: con                                               stant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: con                                               stant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: con                                               stant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: con                                               stant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: con                                               stant Gem::ConfigMap is deprecated
[DEPRECATED] The `--path` flag is deprecated because it relies on being remember                                               ed across bundler invocations, which bundler will no longer do in future version                                               s. Instead please use `bundle config set path 'vendor/bundle'`, and stop using t                                               his flag
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Could not locate Gemfile

ruby --version
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

gem env version
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
3.1.2

My bbb settings:
Ubuntu 16.04 LTS
bbb 2.2.6

Any idea? shall I update ruby? gem? will it affect my bbb instance?
Thanks for your help!

**Comment by alexanderjackson** [comment]
I failed to get this working on Ubuntu 16.04. However, it works with 18.04 as described at https://github.com/bigbluebutton/bbb-events/issues/10#issuecomment-641536062.
