### ISSUE TITLE
ruby need upgrade in ubunt16.04 BBB 220 RC6

### ISSUE THREAD

**Issue by caijian76** [bigbluebutton/bbb-events#8]
When run bundle install --path vendor/bundle , Tips: zeitwerk-2.2.2 requires ruby version >= 2.4.4, which is incompatible with the current version, ruby 2.3.1p112

**Comment by ffdixon** [comment]
> zeitwerk-2.2.2

Is this gem required by a BigBlueButton package -- we're not seeing it on our test servers.

**Comment by alexanderjackson** [comment]
> > zeitwerk-2.2.2
> 
> Is this gem required by a BigBlueButton package -- we're not seeing it on our test servers.

It will still fail when the dependencies is manually removed. I assume the ruby packages in 16.04 are to old. However, it works with 18.04 as described at https://github.com/bigbluebutton/bbb-events/issues/10#issuecomment-641536062.

**Comment by kepstin** [comment]
The latest revisions of this gem no longer support BigBlueButton versions older than 2.5.
